### Importing libraries that will be useful :-

In [2]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')
import scipy
from scipy import stats

# Question 3 solution :

##### Reading population data of males and females from 'DDW_PCA0000_2011_Indiastatedist.xlsx' file which was given in Assignment 1

In [74]:
population_data = pd.read_excel('DDW_PCA0000_2011_Indiastatedist.xlsx',usecols=['Level','Name','TRU','TOT_P'])
population_data_Total = population_data.loc[((population_data['TRU'] == 'Rural') | (population_data['TRU'] == 'Urban')) & (population_data['Level'] == 'STATE')]
population_data_Total = population_data_Total.reset_index()
population_data_Total = population_data_Total.drop(columns=["index","Level"])
population_data_Total.loc[len(population_data_Total.index)] = ['INDIA','Rural',833748852]
population_data_Total.loc[len(population_data_Total.index)] = ['INDIA','Urban',377106125]

population_data_Total = population_data_Total.sort_values('Name',ignore_index=True)
with pd.option_context('display.max_rows', None,'display.max_columns', None,'display.precision', 4,):
    display(population_data_Total)
# population_data_Total#.head()

                         Name    TRU      TOT_P
0   ANDAMAN & NICOBAR ISLANDS  Rural     237093
1   ANDAMAN & NICOBAR ISLANDS  Urban     143488
2              ANDHRA PRADESH  Rural   56361702
3              ANDHRA PRADESH  Urban   28219075
4           ARUNACHAL PRADESH  Rural    1066358
5           ARUNACHAL PRADESH  Urban     317369
6                       ASSAM  Rural   26807034
7                       ASSAM  Urban    4398542
8                       BIHAR  Rural   92341436
9                       BIHAR  Urban   11758016
10                 CHANDIGARH  Rural      28991
11                 CHANDIGARH  Urban    1026459
12               CHHATTISGARH  Urban    5937237
13               CHHATTISGARH  Rural   19607961
14       DADRA & NAGAR HAVELI  Rural     183114
15       DADRA & NAGAR HAVELI  Urban     160595
16                DAMAN & DIU  Rural      60396
17                DAMAN & DIU  Urban     182851
18                        GOA  Rural     551731
19                        GOA  Urban     906814
20                    GUJARAT  Rural   34694609
21                    GUJARAT  Urban   25745083
22                    HARYANA  Rural   16509359
23                    HARYANA  Urban    8842103
24           HIMACHAL PRADESH  Urban     688552
25           HIMACHAL PRADESH  Rural    6176050
26                      INDIA  Rural  833748852
27                      INDIA  Urban  377106125
28            JAMMU & KASHMIR  Urban    3433242
29            JAMMU & KASHMIR  Rural    9108060
30                  JHARKHAND  Rural   25055073
31                  JHARKHAND  Urban    7933061
32                  KARNATAKA  Rural   37469335
33                  KARNATAKA  Urban   23625962
34                     KERALA  Rural   17471135
35                     KERALA  Urban   15934926
36                LAKSHADWEEP  Urban      50332
37                LAKSHADWEEP  Rural      14141
38             MADHYA PRADESH  Urban   20069405
39             MADHYA PRADESH  Rural   52557404
40                MAHARASHTRA  Rural   61556074
41                MAHARASHTRA  Urban   50818259
42                    MANIPUR  Rural    2021640
43                    MANIPUR  Urban     834154
44                  MEGHALAYA  Rural    2371439
45                  MEGHALAYA  Urban     595450
46                    MIZORAM  Rural     525435
47                    MIZORAM  Urban     571771
48                   NAGALAND  Rural    1407536
49                   NAGALAND  Urban     570966
50               NCT OF DELHI  Urban   16368899
51               NCT OF DELHI  Rural     419042
52                     ODISHA  Urban    7003656
53                     ODISHA  Rural   34970562
54                 PUDUCHERRY  Rural     395200
55                 PUDUCHERRY  Urban     852753
56                     PUNJAB  Rural   17344192
57                     PUNJAB  Urban   10399146
58                  RAJASTHAN  Urban   17048085
59                  RAJASTHAN  Rural   51500352
60                     SIKKIM  Rural     456999
61                     SIKKIM  Urban     153578
62                 TAMIL NADU  Rural   37229590
63                 TAMIL NADU  Urban   34917440
64                    TRIPURA  Rural    2712464
65                    TRIPURA  Urban     961453
66              UTTAR PRADESH  Rural  155317278
67              UTTAR PRADESH  Urban   44495063
68                UTTARAKHAND  Rural    7036954
69                UTTARAKHAND  Urban    3049338
70                WEST BENGAL  Rural   62183113
71                WEST BENGAL  Urban   29093002

In [76]:
# list = ['Name','Rural','Urban']
# temp_d2 = pd.DataFrame(columns=list)
pre_final1 = pd.DataFrame()
# i = 0
# while i < len(population_data_Total.index):
#     temp_d2['Name'] = [population_data_Total.iat[i,0]]
#     temp_d2['Rural'] = population_data_Total.iat[i,2]
#     temp_d2['Urban'] = population_data_Total.iat[i+1,2]
#     pre_final1 = pre_final1.append(temp_d2, ignore_index=True)
#     if i == 68:
#         i += 1
#     else: 
#         i += 2
# pre_final1#.head()
# # with pd.option_context('display.max_rows', None,'display.max_columns', None,'display.precision', 4,):
#     display(pre_final1)


pre_final1 = population_data_Total.reset_index().groupby(['Name', 'TRU'])['TOT_P'].aggregate('first').unstack()
pre_final1.reset_index(level=0, inplace=True)
# pre_final1["Rural"] = pre_final1["Rural"].astype(int)
# pre_final1["Urban"] = pre_final1["Urban"].astype(int)
pre_final1.columns=['Name','Rural','Urban']
pre_final1

                         Name      Rural      Urban
0   ANDAMAN & NICOBAR ISLANDS     237093     143488
1              ANDHRA PRADESH   56361702   28219075
2           ARUNACHAL PRADESH    1066358     317369
3                       ASSAM   26807034    4398542
4                       BIHAR   92341436   11758016
5                  CHANDIGARH      28991    1026459
6                CHHATTISGARH   19607961    5937237
7        DADRA & NAGAR HAVELI     183114     160595
8                 DAMAN & DIU      60396     182851
9                         GOA     551731     906814
10                    GUJARAT   34694609   25745083
11                    HARYANA   16509359    8842103
12           HIMACHAL PRADESH    6176050     688552
13                      INDIA  833748852  377106125
14            JAMMU & KASHMIR    9108060    3433242
15                  JHARKHAND   25055073    7933061
16                  KARNATAKA   37469335   23625962
17                     KERALA   17471135   15934926
18                LAKSHADWEEP      14141      50332
19             MADHYA PRADESH   52557404   20069405
20                MAHARASHTRA   61556074   50818259
21                    MANIPUR    2021640     834154
22                  MEGHALAYA    2371439     595450
23                    MIZORAM     525435     571771
24                   NAGALAND    1407536     570966
25               NCT OF DELHI     419042   16368899
26                     ODISHA   34970562    7003656
27                 PUDUCHERRY     395200     852753
28                     PUNJAB   17344192   10399146
29                  RAJASTHAN   51500352   17048085
30                     SIKKIM     456999     153578
31                 TAMIL NADU   37229590   34917440
32                    TRIPURA    2712464     961453
33              UTTAR PRADESH  155317278   44495063
34                UTTARAKHAND    7036954    3049338
35                WEST BENGAL   62183113   29093002

In [77]:
pre_final1.dtypes

Name     object
Rural     int64
Urban     int64
dtype: object

##### Reading language data from 'DDW-C18-0000.xlsx' file which is mentioned in Assignment 2

In [94]:
Language_data= pd.read_excel('DDW-C18-0000.xlsx',usecols=['Unnamed: 0','Unnamed: 2','Unnamed: 3','Unnamed: 4','Unnamed: 5','Unnamed: 8'])
Language_data.rename(columns = {'Unnamed: 0':'Code','Unnamed: 2':'Name','Unnamed: 3':'TRU','Unnamed: 4':'Age_group',
                                'Unnamed: 5':'People speaking 2 or more languaguages',
                                'Unnamed: 8':'People speaking 3 or more languaguages',}, inplace = True)

Language_data = Language_data.drop(Language_data.index[[0,1,2,3,4]])
Language_data = Language_data.loc[((Language_data['TRU'] == 'Rural') | (Language_data['TRU'] == 'Urban')) & (Language_data['Age_group'] == 'Total')]
Language_data = Language_data.reset_index()
Language_data = Language_data.drop(columns=["index","Age_group"])
# Language_data = Language_data.sort_values('Code',ignore_index=True)
Language_data["Code"] = Language_data["Code"].astype(int)

Language_data = Language_data.sort_values('Code',ignore_index=True)
# with pd.option_context('display.max_rows', None,'display.max_columns', None,'display.precision', 4,):
#     display(Language_data)
Language_data.head(5)

,Code,Name,TRU,People speaking 2 or more languaguages,People speaking 3 or more languaguages
0,0,INDIA,Rural,162641485,35383989
1,0,INDIA,Urban,152347285,50625591
2,1,JAMMU & KASHMIR,Rural,4167238,1258724
3,1,JAMMU & KASHMIR,Urban,2015952,837496
4,2,HIMACHAL PRADESH,Rural,981518,280817

In [106]:
list = ['Code','Name','People speaking 2 or more languaguages (Rural)','People speaking 2 or more languaguages (Urban)','People speaking 3 or more languaguages (Rural)','People speaking 3 or more languaguages (Urban)']
temp_d3 = pd.DataFrame(columns=list)
pre_final2 = pd.DataFrame()
i = 0
while i < len(Language_data.index):
    temp_d3['Code'] = [Language_data.iat[i,0]]    
    temp_d3['Name'] = [Language_data.iat[i,1]]
    temp_d3['People speaking 2 or more languaguages (Rural)'] = Language_data.iat[i,3]
    temp_d3['People speaking 2 or more languaguages (Urban)'] = Language_data.iat[i+1,3]
    temp_d3['People speaking 3 or more languaguages (Rural)'] = [Language_data.iat[i,4]]
    temp_d3['People speaking 3 or more languaguages (Urban)'] = [Language_data.iat[i+1,4]]    
#     pre_final2 = pre_final2.append(temp_d3, ignore_index=True)
    if i == 69:
        i += 1
    else: 
        i += 2
#     break
pre_final2 = Language_data.reset_index().groupby(['Code','Name','TRU'])[['People speaking 2 or more languaguages','People speaking 3 or more languaguages']].aggregate('first').unstack()
pre_final2 = pre_final2.reset_index()
pre_final2.columns = ['Code','Name','People speaking 2 or more languaguages (Rural)','People speaking 2 or more languaguages (Urban)','People speaking 3 or more languaguages (Rural)','People speaking 3 or more languaguages (Urban)']
pre_final2["Code"] = pre_final2["Code"].astype(str).astype(int)
pre_final2 = pre_final2.sort_values('Code',ignore_index=True)
pre_final2#.head()

,Code,Name,People speaking 2 or more languaguages (Rural),People speaking 2 or more languaguages (Urban),People speaking 3 or more languaguages (Rural),People speaking 3 or more languaguages (Urban)
0,0,INDIA,162641485,152347285,35383989,50625591
1,1,JAMMU & KASHMIR,4167238,2015952,1258724,837496
2,2,HIMACHAL PRADESH,981518,261187,280817,66469
3,3,PUNJAB,7083180,5952044,4230870,3599043
4,4,CHANDIGARH,11723,568197,4353,317626
5,5,UTTARAKHAND,835231,922525,70611,117211
6,6,HARYANA,2757542,2869819,562967,607604
7,7,NCT OF DELHI,98713,6718501,5474,1352759
8,8,RAJASTHAN,4247026,3226160,609507,397244
9,9,UTTAR PRADESH,10917897,11955712,1267848,1317816
10,10,BIHAR,13930257,2831528,1262676,419896
11,11,SIKKIM,274230,114769,118176,63226
12,12,ARUNACHAL PRADESH,658664,227281,292514,126037
13,13,NAGALAND,805544,424179,306186,231295
14,14,MANIPUR,957878,430742,376083,240735
15,15,MIZORAM,123209,186494,18117,34849
16,16,TRIPURA,998741,269860,111473,87104
17,17,MEGHALAYA,473698,348622,123303,151628
18,18,ASSAM,11781858,2678733,2969373,1383124
19,19,WEST BENGAL,6968587,8057261,664075,2216930
20,20,JHARKHAND,6988351,3012369,932202,660837
21,21,ODISHA,10031393,3793631,3361065,2164213
22,22,CHHATTISGARH,2094811,1289412,197443,225126
23,23,MADHYA PRADESH,5329355,4479327,562738,695215
24,24,GUJARAT,11448340,14444001,3031288,5539283
25,25,DAMAN & DIU,28799,87830,7809,26793
26,26,DADRA & NAGAR HAVELI,110332,88651,39658,31858
27,27,MAHARASHTRA,24378668,33041193,6072975,13651754
28,28,ANDHRA PRADESH,10862432,10720902,2361512,3982864
29,29,KARNATAKA,10742452,13510142,2048187,5783942
30,30,GOA,412842,713310,261781,479468
31,31,LAKSHADWEEP,3507,15046,2007,7974
32,32,KERALA,3813471,4349916,1360343,1828470
33,33,TAMIL NADU,8090417,12325853,568669,1878494
34,34,PUDUCHERRY,80981,311311,5029,66636
35,35,ANDAMAN & NICOBAR ISLANDS,152600,104825,38136,34572

In [107]:
Processed_data = pd.merge(pre_final1,pre_final2,left_on = 'Name', right_on = 'Name')

# Processed_data['TOT_A'] = Processed_data['TOT_P'] - Processed_data['People_speaking_2_languaguages']
# Processed_data['People_speaking_2_languaguages'] -= Processed_data['People_speaking_3_languaguages']
# Processed_data.rename(columns = {'TOT_A':'No_PSE_1_language',
#                                  'People_speaking_2_languaguages':'No_PSE_2_language',
#                                 'People_speaking_3_languaguages':'No_PSE_3_language'}, inplace = True)
''' 
    No.PSE means Number of People Speaking Exactly
'''
# Processed_data.iat[0,0] = 'INDIA'
# Processed_data = Processed_data[['Name','TOT_P','No_PSE_1_language','No_PSE_2_language','No_PSE_3_language']]
Processed_data = Processed_data.sort_values('Code',ignore_index=True)
Processed_data.head(5)

,Name,Rural,Urban,Code,People speaking 2 or more languaguages (Rural),People speaking 2 or more languaguages (Urban),People speaking 3 or more languaguages (Rural),People speaking 3 or more languaguages (Urban)
0,INDIA,833748852,377106125,0,162641485,152347285,35383989,50625591
1,JAMMU & KASHMIR,9108060,3433242,1,4167238,2015952,1258724,837496
2,HIMACHAL PRADESH,6176050,688552,2,981518,261187,280817,66469
3,PUNJAB,17344192,10399146,3,7083180,5952044,4230870,3599043
4,CHANDIGARH,28991,1026459,4,11723,568197,4353,317626

In [108]:
Processed_Data = Processed_data.copy()

Processed_Data['Percentage rural speaking only 1 language'] = ((Processed_Data['Rural'] - Processed_Data['People speaking 2 or more languaguages (Rural)']) / Processed_Data['Rural']) * 100
Processed_Data['Percentage rural speaking exactly 2 language'] = ((Processed_Data['People speaking 2 or more languaguages (Rural)'] - Processed_Data['People speaking 3 or more languaguages (Rural)']) / Processed_Data['Rural']) * 100
Processed_Data['Percentage rural speaking 3 or more languaguages'] = ((Processed_Data['People speaking 3 or more languaguages (Rural)']) / Processed_Data['Rural']) * 100

Processed_Data['Percentage urban speaking only 1 language'] = ((Processed_Data['Urban'] - Processed_Data['People speaking 2 or more languaguages (Urban)']) / Processed_Data['Urban']) * 100
Processed_Data['Percentage urban speaking exactly 2 language'] = ((Processed_Data['People speaking 2 or more languaguages (Urban)'] - Processed_Data['People speaking 3 or more languaguages (Urban)']) / Processed_Data['Urban']) * 100
Processed_Data['Percentage urban speaking 3 or more languaguages'] = (Processed_Data['People speaking 3 or more languaguages (Urban)'] / Processed_Data['Urban']) * 100

Processed_Data['ratio_1'] = (Processed_Data['Urban'] - Processed_Data['People speaking 2 or more languaguages (Urban)']) / (Processed_Data['Rural']-Processed_Data['People speaking 2 or more languaguages (Rural)'])
Processed_Data['ratio_2'] = (Processed_Data['People speaking 2 or more languaguages (Urban)'] - Processed_Data['People speaking 3 or more languaguages (Urban)']) / (Processed_Data['People speaking 2 or more languaguages (Rural)'] - Processed_Data['People speaking 3 or more languaguages (Rural)'])
Processed_Data['ratio_3'] = Processed_Data['People speaking 3 or more languaguages (Urban)'] / Processed_Data['People speaking 3 or more languaguages (Rural)']
Processed_Data['ratio_pop'] = Processed_Data['Urban'] / Processed_Data['Rural']

Processed_Data['p-value'] = Processed_Data.apply(lambda row: scipy.stats.ttest_1samp([row.ratio_1, row.ratio_2, row.ratio_3], popmean=row.ratio_pop)[1], axis=1)

Processed_Data = Processed_Data[['Code','Name','Percentage rural speaking only 1 language',
                                 'Percentage urban speaking only 1 language',
                                 'Percentage rural speaking exactly 2 language',
                                 'Percentage urban speaking exactly 2 language',
                                 'Percentage rural speaking 3 or more languaguages',
                                 'Percentage urban speaking 3 or more languaguages','p-value']]
                                                                       
Processed_Data#.head()

,Code,Name,Percentage rural speaking only 1 language,Percentage urban speaking only 1 language,Percentage rural speaking exactly 2 language,Percentage urban speaking exactly 2 language,Percentage rural speaking 3 or more languaguages,Percentage urban speaking 3 or more languaguages,p-value
0,0,INDIA,80.492749,59.600952,15.263289,26.974288,4.243963,13.424760,0.332407
1,1,JAMMU & KASHMIR,54.246700,41.281389,31.933408,34.324874,13.819891,24.393736,0.568997
2,2,HIMACHAL PRADESH,84.107674,62.067208,11.345455,28.279346,4.546871,9.653447,0.279581
3,3,PUNJAB,59.161084,42.764108,16.445332,22.626868,24.393584,34.609025,0.523689
4,4,CHANDIGARH,59.563313,44.644940,25.421683,24.411204,15.015005,30.943857,0.592084
5,5,UTTARAKHAND,88.130788,69.746712,10.865781,26.409470,1.003431,3.843818,0.263868
6,6,HARYANA,83.297098,67.543705,13.292915,25.584581,3.409987,6.871714,0.270791
7,7,NCT OF DELHI,76.443173,58.955694,22.250514,32.780103,1.306313,8.264203,0.399070
8,8,RAJASTHAN,91.753404,81.076115,7.063095,16.593746,1.183501,2.330139,0.236601
9,9,UTTAR PRADESH,92.970584,73.130250,6.213120,23.908037,0.816296,2.961713,0.217139
10,10,BIHAR,84.914403,75.918318,13.718198,20.510535,1.367399,3.571147,0.316182
11,11,SIKKIM,39.993304,25.269895,34.147558,33.561448,25.859138,41.168657,0.828855
12,12,ARUNACHAL PRADESH,38.232376,28.385885,34.336499,31.901036,27.431125,39.713078,0.867929
13,13,NAGALAND,42.769208,25.708536,35.477458,33.782047,21.753333,40.509417,0.747793
14,14,MANIPUR,52.618765,48.361813,28.778368,22.778408,18.602867,28.859779,0.745795
15,15,MIZORAM,76.551048,67.383096,20.000952,26.521982,3.448000,6.094923,0.332646
16,16,TRIPURA,63.179567,71.932065,32.710775,19.008313,4.109658,9.059621,0.584067
17,17,MEGHALAYA,80.024871,41.452347,14.775628,33.083214,5.199501,25.464439,0.347429
18,18,ASSAM,56.049379,39.099524,32.873779,29.455420,11.076843,31.445056,0.556900
19,19,WEST BENGAL,88.793441,72.305158,10.138624,20.074694,1.067935,7.620149,0.356353
20,20,JHARKHAND,72.108040,62.027659,24.171348,29.642177,3.720612,8.330164,0.396087
21,21,ODISHA,71.314750,45.833562,19.074123,23.265249,9.611127,30.901189,0.467962
22,22,CHHATTISGARH,89.316528,78.282625,9.676519,17.925611,1.006953,3.791764,0.303476
23,23,MADHYA PRADESH,89.859935,77.680818,9.069354,18.855128,1.070711,3.464054,0.261701
24,24,GUJARAT,67.002539,43.896079,24.260403,34.588034,8.737058,21.515887,0.429452
25,25,DAMAN & DIU,52.316379,51.966355,34.753957,33.380731,12.929664,14.652914,0.638774
26,26,DADRA & NAGAR HAVELI,39.746824,44.798406,38.595629,35.364115,21.657547,19.837479,0.864934
27,27,MAHARASHTRA,60.395999,34.981651,29.738240,38.154473,9.865761,26.863876,0.490434
28,28,ANDHRA PRADESH,80.727282,62.008315,15.082795,23.877601,4.189923,14.114084,0.359147
29,29,KARNATAKA,71.330017,42.816542,23.203681,32.702160,5.466302,24.481297,0.428730
30,30,GOA,25.173318,21.338885,27.379466,25.787207,47.447216,52.873908,0.721405
31,31,LAKSHADWEEP,75.199774,70.106493,10.607454,14.050703,14.192773,15.842804,0.386916
32,32,KERALA,78.172735,72.702001,14.041034,15.823393,7.786231,11.474606,0.381538
33,33,TAMIL NADU,78.268853,64.700010,20.203682,29.920175,1.527465,5.379816,0.365153
34,34,PUDUCHERRY,79.508856,63.493415,19.218623,28.692365,1.272520,7.814221,0.393157
35,35,ANDAMAN & NICOBAR ISLANDS,35.637071,26.945110,48.278102,48.960889,16.084827,24.094001,0.720846

In [83]:

final_1 = Processed_Data[['Code','Name','Percentage rural speaking only 1 language','Percentage urban speaking only 1 language','p-value']].copy()
final_2 = Processed_Data[['Code','Name','Percentage rural speaking exactly 2 language','Percentage urban speaking exactly 2 language','p-value']].copy()
final_3 = Processed_Data[['Code','Name','Percentage rural speaking 3 or more languaguages','Percentage urban speaking 3 or more languaguages','p-value']].copy()

final_1.columns=['State_code','Name','rural-percentage','urban-percentage','p-value']
final_2.columns=['State_code','Name','rural-percentage','urban-percentage','p-value']
final_3.columns=['State_code','Name','rural-percentage','urban-percentage','p-value']

final_1.to_csv('gender-india-a.csv')
final_2.to_csv('gender-india-b.csv')
final_3.to_csv('gender-india-c.csv')

## Q3 Completed..:)